// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Newtonsoft.Json.FSharp.Idiomatic.Tests")>]
[<assembly: AssemblyProductAttribute("Newtonsoft.Json.FSharp.Idiomatic")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2018-05-20T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","e3d6220d3ffab04b27e0c730438f08fbfe1cbb12")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Newtonsoft.Json.FSharp.Idiomatic.Tests"
    let [<Literal>] AssemblyProduct = "Newtonsoft.Json.FSharp.Idiomatic"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2018-05-20T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "e3d6220d3ffab04b27e0c730438f08fbfe1cbb12"
